/**
 * Keeps create-iskra's bundled data in sync with the monorepo:
 *
 *  - `templates/<name>/` is a copy of the monorepo's `templates/<name>/`, except
 *    standalone variants of files that only work inside the monorepo:
 *    `tsconfig.json` (extends `../../tsconfig.base.json`), `Dockerfile` (built
 *    from the repository root, with the workspace lockfile) and `.dockerignore`.
 *  - `src/versions.ts` records the current version of every publishable
 *    `@iskra-bun/*` package, used to turn `workspace:*` into installable ranges.
 *
 * Usage: `bun run scripts/sync.ts` rewrites the bundled copies;
 * `bun run scripts/sync.ts --check` only reports drift and exits 1 if any.
 * Runs as part of the root `version` script so release PRs stay in sync, and
 * test/bundled-templates.test.ts fails CI when someone forgets.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const PACKAGE_DIR = join(import.meta.dir, '..');
const REPO_ROOT = join(PACKAGE_DIR, '..', '..');

/** Monorepo templates that ship inside the create-iskra package. */
export const BUNDLED_TEMPLATES = ['simple-server', 'starter-app'] as const;

/** Files that intentionally differ between the monorepo template and the bundled copy. */
const STANDALONE_FILES = new Set(['tsconfig.json', 'Dockerfile', '.dockerignore']);
const SKIPPED_DIRS = new Set(['node_modules', 'dist', '.git']);

export const VERSIONS_FILE = join(PACKAGE_DIR, 'src', 'versions.ts');

export function listFiles(dir: string, base = dir): string[] {
    if (!existsSync(dir)) return [];
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        if (SKIPPED_DIRS.has(entry.name)) return [];
        const path = join(dir, entry.name);
        if (entry.isDirectory()) return listFiles(path, base);
        // readFileSync follows a symlink: one to /proc/self/environ or to a
        // file outside the template was copied into the published package,
        // by a release job that has the npm and GitHub tokens in its env.
        if (!entry.isFile()) {
            throw new Error(
                `${relative(base, path)} in ${dir} is not a regular file; templates cannot contain symlinks`,
            );
        }
        return [relative(base, path)];
    });
}

/** Publishable `@iskra-bun/*` package versions, sorted by name. */
export function workspaceVersions(): Record<string, string> {
    const versions: Record<string, string> = {};
    for (const entry of readdirSync(join(REPO_ROOT, 'packages'), { withFileTypes: true })) {
        const manifestPath = join(REPO_ROOT, 'packages', entry.name, 'package.json');
        if (!entry.isDirectory() || !existsSync(manifestPath)) continue;
        const { name, version, private: isPrivate } = JSON.parse(readFileSync(manifestPath, 'utf8'));
        if (typeof name === 'string' && name.startsWith('@iskra-bun/') && !isPrivate) {
            versions[name] = version;
        }
    }
    return Object.fromEntries(Object.entries(versions).sort(([a], [b]) => a.localeCompare(b)));
}

export function renderVersionsFile(versions: Record<string, string>): string {
    const lines = Object.entries(versions).map(([name, version]) => `    '${name}': '${version}',`);
    return [
        '// Generated by scripts/sync.ts from packages/*/package.json — do not edit by hand.',
        '// Run `bun run scripts/sync.ts` (from packages/create-iskra) after bumping versions.',
        '',
        '/** Current version of every publishable `@iskra-bun/*` package. */',
        'export const ISKRA_VERSIONS: Readonly<Record<string, string>> = {',
        ...lines,
        '};',
        '',
    ].join('\n');
}

export type Drift =
    | { readonly kind: 'write'; readonly path: string; readonly content: Buffer | string }
    | { readonly kind: 'delete'; readonly path: string };

/** Computes every write/delete needed to bring the bundled data in sync. Pure w.r.t. the filesystem. */
export function planSync(): Drift[] {
    const drift: Drift[] = [];

    for (const name of BUNDLED_TEMPLATES) {
        const sourceDir = join(REPO_ROOT, 'templates', name);
        const bundledDir = join(PACKAGE_DIR, 'templates', name);
        const sourceFiles = listFiles(sourceDir).filter((f) => !STANDALONE_FILES.has(f));

        for (const file of sourceFiles) {
            const content = readFileSync(join(sourceDir, file));
            const target = join(bundledDir, file);
            if (!existsSync(target) || !readFileSync(target).equals(content)) {
                drift.push({ kind: 'write', path: target, content });
            }
        }
        for (const file of listFiles(bundledDir)) {
            if (!STANDALONE_FILES.has(file) && !sourceFiles.includes(file)) {
                drift.push({ kind: 'delete', path: join(bundledDir, file) });
            }
        }
    }

    const versions = renderVersionsFile(workspaceVersions());
    if (!existsSync(VERSIONS_FILE) || readFileSync(VERSIONS_FILE, 'utf8') !== versions) {
        drift.push({ kind: 'write', path: VERSIONS_FILE, content: versions });
    }

    return drift;
}

function main() {
    const drift = planSync();
    const check = process.argv.includes('--check');

    for (const change of drift) {
        const label = relative(REPO_ROOT, change.path);
        if (check) {
            process.stdout.write(`out of sync: ${label}\n`);
        } else if (change.kind === 'write') {
            mkdirSync(dirname(change.path), { recursive: true });
            writeFileSync(change.path, change.content);
            process.stdout.write(`updated ${label}\n`);
        } else {
            rmSync(change.path);
            process.stdout.write(`deleted ${label}\n`);
        }
    }

    if (check && drift.length > 0) {
        process.stderr.write('create-iskra is out of sync; run `bun run scripts/sync.ts` in packages/create-iskra\n');
        process.exit(1);
    }
    process.stdout.write(`✓ create-iskra in sync (${drift.length} change(s)${check ? ' found' : ' applied'})\n`);
}

if (import.meta.main) main();
