// Generated by scripts/sync.ts from packages/*/package.json — do not edit by hand.
// Run `bun run scripts/sync.ts` (from packages/create-iskra) after bumping versions.

/** Current version of every publishable `@iskra-bun/*` package. */
export const ISKRA_VERSIONS: Readonly<Record<string, string>> = {
    '@iskra-bun/auth-kit': '0.1.0',
    '@iskra-bun/cache-kit': '0.1.0',
    '@iskra-bun/config-kit': '0.1.0',
    '@iskra-bun/core': '0.1.1',
    '@iskra-bun/db-kit': '0.2.0',
    '@iskra-bun/db-oracle': '0.1.1',
    '@iskra-bun/desktop-kit': '0.1.1',
    '@iskra-bun/kv-kit': '0.2.0',
    '@iskra-bun/mailer-kit': '0.1.0',
    '@iskra-bun/mobile-kit': '0.1.1',
    '@iskra-bun/process-kit': '0.2.0',
    '@iskra-bun/socket-kit': '0.2.0',
    '@iskra-bun/storage-kit': '0.1.0',
    '@iskra-bun/testing-kit': '0.1.0',
    '@iskra-bun/web-kit': '0.2.0',
    '@iskra-bun/worker-kit': '0.2.0',
};
