import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { Feature, OpenAPIConfig } from '../types';
import type { Kernel } from '../kernel';
import type { Context, Handler, Hono, Next } from 'hono';
import { OpenAPIHono, createRoute, z, type RouteConfig } from '@hono/zod-openapi';
import { ErrorCodes } from '../responses';
import { problem, responderOf } from '../contract';
import { consoleLogger, type KernelLogger } from '../logging';
import { documentRoutes, type RoutesDocument } from '../openapi-routes';
import { withRouteDoc } from '../route-docs';

/**
 * The API reference /docs loads: one release, with the SRI hash of that exact
 * file (the same bytes as in its npm tarball). `@latest` ran whatever Scalar
 * published last on the app's origin, with access to its cookies and storage.
 */
const SCALAR_SCRIPT = {
    src: 'https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.68.0/dist/browser/standalone.js',
    integrity: 'sha384-PhSzhE9ihf7z/cKeRSKAeP+oJMMzotyFv0EjvNYgL798a2ODBQVuJLTP4Klle6IB',
};

const DEFAULT_SERVERS = [{ url: 'http://localhost:8000', description: 'Dev Server' }];

/** Where `/docs` loads Scalar from with `scalar: 'local'` or `{ file }`. */
const LOCAL_SCALAR_PATH = '/docs/scalar.js';

/** The docs' own routes stay out of the spec. */
const hidden = <H extends object>(handler: H): H => withRouteDoc(handler, { describe: { hidden: true } });

/**
 * Scalar's browser bundle in the installed @scalar/api-reference (an
 * optional peer dependency), looked up from web-kit and from the app.
 */
function installedScalar(): string {
    for (const base of [import.meta.url, pathToFileURL(join(process.cwd(), 'package.json')).href]) {
        try {
            // dist/index.js → dist/browser/standalone.js
            const file = join(
                dirname(createRequire(base).resolve('@scalar/api-reference')),
                'browser',
                'standalone.js',
            );
            if (existsSync(file)) return file;
        } catch {
            // Not installed where this base resolves.
        }
    }
    throw new Error("OpenAPIFeature: scalar: 'local' needs @scalar/api-reference (bun add @scalar/api-reference)");
}

/** The spec's paths, by path and method. */
type Existing = Record<string, Record<string, unknown> | undefined>;

interface ScalarAsset {
    body: Uint8Array;
    integrity: string;
    etag: string;
}

const escapeHtml = (value: string): string => value.replace(/[&<>"']/g, (ch) => `&#${ch.charCodeAt(0)};`);

/** The origin of an absolute http(s) URL, or null. */
function httpOrigin(url: string): string | null {
    try {
        const parsed = new URL(url);
        return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.origin : null;
    } catch {
        return null;
    }
}

export class OpenAPIFeature implements Feature {
    name = 'openapi';
    private log: KernelLogger = consoleLogger;
    private app?: OpenAPIHono;
    private config: OpenAPIConfig;
    private kernel?: Kernel;
    private autoGeneratedRoutes: Array<{ path: string; method: string; tags: string[]; summary: string }> = [];
    private queuedRoutes: Array<{ route: RouteConfig; handler: Handler }> = [];
    /** The kernel's app once routes() mounted this feature's routes on it. */
    private mountedOn?: Hono;
    /** The spec of the app's own routes, for as many routes as the app had. */
    private routesDoc?: { count: number; doc: RoutesDocument };
    private scalarAsset?: Promise<ScalarAsset>;

    constructor(config: OpenAPIConfig) {
        this.config = config;
    }

    async initialize(kernel: Kernel): Promise<void> {
        this.log = kernel.getLogger();
        this.kernel = kernel;
        this.app = this.newApp();

        this.processQueuedRoutes();
        this.log.debug('OpenAPIFeature initialized');
    }

    addRoute(route: RouteConfig, handler: Handler) {
        if (!this.app) {
            this.queuedRoutes.push({ route, handler });
            return;
        }
        this.app.openapi(createRoute(route), handler);
        // Hono copies a sub-app's routes when it is mounted: a route added
        // afterwards appeared in /openapi.json but answered 404.
        if (this.mountedOn) this.mountedOn.route('/', this.routeApp(route, handler));
        this.autoGeneratedRoutes.push({
            path: route.path,
            method: route.method.toUpperCase(),
            tags: route.tags || [],
            summary: route.summary || '',
        });
    }

    private processQueuedRoutes() {
        if (!this.app) return;
        for (const { route, handler } of this.queuedRoutes) {
            this.addRoute(route, handler);
        }
        this.queuedRoutes = [];
    }

    private newApp(): OpenAPIHono {
        return new OpenAPIHono({
            defaultHook: (result, c: Context) => {
                if (!result.success) {
                    return responderOf(c).problem(
                        c,
                        problem(400, {
                            code: ErrorCodes.VALIDATION_ERROR,
                            message: 'Validation Error',
                            details: result.error.flatten(),
                        }),
                    );
                }
            },
        });
    }

    /** A sub-app with just this route, to mount after the others. */
    private routeApp(route: RouteConfig, handler: Handler): OpenAPIHono {
        const app = this.newApp();
        app.openapi(createRoute(route), handler);
        return app;
    }

    routes(app: Hono) {
        if (this.app) {
            app.route('/', this.app);
            this.mountedOn = app;
        }

        if (this.config.docs === false) return;

        // These routes come before any middleware the app adds after
        // initialize(), so an auth middleware there did not cover them.
        const authorize = this.config.authorize;
        const guard = async (c: Context, next: Next) => {
            const decision = authorize ? await authorize(c) : true;
            if (decision instanceof Response) return decision;
            if (!decision) return responderOf(c).problem(c, problem(403));
            await next();
        };

        app.get(
            '/openapi.json',
            hidden(guard),
            hidden((c: Context) => {
                if (!this.app) return responderOf(c).problem(c, problem(500, { message: 'OpenAPI not initialized' }));

                const spec = this.app.getOpenAPIDocument({
                    openapi: '3.1.0',
                    info: {
                        title: this.config.title,
                        version: this.config.version,
                        description: this.config.description || 'API Documentation',
                        contact: this.config.contact,
                        license: this.config.license,
                    },
                    servers: this.config.servers || DEFAULT_SERVERS,
                    tags: this.config.tags || [],
                    externalDocs: this.config.externalDocs,
                    security: this.config.security,
                });

                const routes =
                    this.config.routes === false ? undefined : this.routesDocument(app, (spec.paths ?? {}) as Existing);
                if (routes) {
                    spec.paths = { ...spec.paths };
                    for (const [path, item] of Object.entries(routes.paths)) {
                        spec.paths[path] = { ...item, ...spec.paths[path] } as (typeof spec.paths)[string];
                    }
                }
                const schemas = { ...routes?.schemas, ...spec.components?.schemas };
                const securitySchemes = {
                    ...routes?.securitySchemes,
                    ...spec.components?.securitySchemes,
                    ...this.config.securitySchemes,
                };
                if (Object.keys(schemas).length > 0 || Object.keys(securitySchemes).length > 0) {
                    spec.components = {
                        ...spec.components,
                        ...(Object.keys(schemas).length > 0 ? { schemas: schemas as never } : {}),
                        ...(Object.keys(securitySchemes).length > 0
                            ? { securitySchemes: securitySchemes as never }
                            : {}),
                    };
                }

                return c.json(spec);
            }),
        );

        const option = this.config.scalar ?? SCALAR_SCRIPT;
        if (option === false) return;
        const file = option === 'local' ? installedScalar() : 'file' in option ? option.file : undefined;
        if (file !== undefined) {
            // The bundle is public code: it is served without asking authorize().
            app.get(
                LOCAL_SCALAR_PATH,
                hidden(async (c: Context) => {
                    const asset = await this.loadScalar(file);
                    const headers = { ETag: asset.etag, 'Cache-Control': 'no-cache' };
                    if (c.req.header('If-None-Match') === asset.etag) return c.body(null, 304, headers);
                    return c.body(asset.body as Uint8Array<ArrayBuffer>, 200, {
                        ...headers,
                        'Content-Type': 'text/javascript; charset=utf-8',
                    });
                }),
            );
        }
        app.get(
            '/docs',
            hidden(guard),
            hidden(async (c: Context) => {
                const script =
                    file === undefined
                        ? (option as { src: string; integrity: string })
                        : { src: LOCAL_SCALAR_PATH, integrity: (await this.loadScalar(file)).integrity };
                c.header('Content-Security-Policy', this.docsPolicy(script.src));
                return c.html(this.generateScalarHTML(script));
            }),
        );
    }

    /** The spec of the app's routes other than addRoute()'s, made again when routes are added. */
    private routesDocument(app: Hono, existing: Existing): RoutesDocument {
        const count = app.routes.length;
        if (this.routesDoc?.count !== count) {
            const doc = documentRoutes(app.routes, {
                include: this.config.routes || 'described',
                contract: this.kernel?.getResponder().contract,
                skip: (method, path) => existing[path]?.[method.toLowerCase()] !== undefined,
            });
            this.routesDoc = { count, doc };
        }
        return this.routesDoc.doc;
    }

    /** Scalar's bundle from disk, read once, with its SRI hash. */
    private loadScalar(file: string): Promise<ScalarAsset> {
        this.scalarAsset ??= readFile(file).then(
            (body) => {
                const digest = createHash('sha384').update(body).digest('base64');
                return { body, integrity: `sha384-${digest}`, etag: `"${digest.slice(0, 32)}"` };
            },
            (error: unknown) => {
                this.scalarAsset = undefined;
                throw error;
            },
        );
        return this.scalarAsset;
    }

    /**
     * The docs page's CSP: the pinned script, the inline styles Scalar
     * injects, and requests to this origin and the spec's servers ("Try it")
     * only, so the page loads and sends nothing anywhere else.
     */
    private docsPolicy(scriptSrc: string): string {
        const servers = (this.config.servers || DEFAULT_SERVERS).map((server) => httpOrigin(server.url));
        const connect = ["'self'", ...new Set(servers.filter((origin): origin is string => origin !== null))];
        return [
            "default-src 'none'",
            `script-src ${httpOrigin(scriptSrc) ?? "'self'"}`,
            "style-src 'unsafe-inline'",
            "img-src 'self' data: https:",
            "font-src 'self' data:",
            `connect-src ${connect.join(' ')}`,
            "base-uri 'none'",
            "form-action 'none'",
            "frame-ancestors 'self'",
        ].join('; ');
    }

    private generateScalarHTML(script: { src: string; integrity: string }): string {
        // Without withDefaultFonts: false Scalar loads fonts from fonts.scalar.com,
        // and its AI agent (on by default on localhost) sends the spec to api.scalar.com.
        return `
<!DOCTYPE html>
<html>
<head>
    <title>${escapeHtml(this.config.title)} - API Documentation</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>body { margin: 0; padding: 0; }</style>
</head>
<body>
    <script id="api-reference" data-url="/openapi.json" data-configuration='{"theme":"purple","layout":"modern","showSidebar":true,"withDefaultFonts":false,"agent":{"disabled":true}}'></script>
    <script src="${escapeHtml(script.src)}" integrity="${escapeHtml(script.integrity)}" crossorigin="anonymous"></script>
</body>
</html>`.trim();
    }
}

export { createRoute, OpenAPIHono, z };
