import type { Feature, OpenAPIConfig } from "../types";
import type { Kernel } from "../kernel";
import type { Context, Handler, Hono } from "hono";
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import { ErrorCodes, errorResponse } from "../responses";

export class OpenAPIFeature implements Feature {
    name = "openapi";
    private app?: OpenAPIHono;
    private config: OpenAPIConfig;
    private kernel?: Kernel;
    private autoGeneratedRoutes: Array<{ path: string; method: string; tags: string[]; summary: string }> = [];
    private queuedRoutes: Array<{ route: any; handler: Handler }> = [];

    constructor(config: OpenAPIConfig) {
        this.config = config;
    }

    async initialize(kernel: Kernel): Promise<void> {
        this.kernel = kernel;
        this.app = new OpenAPIHono({
            defaultHook: (result: any, c: Context) => {
                if (!result.success) {
                    return c.json(errorResponse("Validation Error", ErrorCodes.VALIDATION_ERROR, result.error.flatten()), 400);
                }
            }
        });

        this.processQueuedRoutes();
        console.log("✅ OpenAPIFeature initialized");
    }

    addRoute(route: any, handler: Handler) {
        if (!this.app) {
            this.queuedRoutes.push({ route, handler });
            return;
        }
        this.app.openapi(createRoute(route), handler);
        this.autoGeneratedRoutes.push({
            path: route.path,
            method: route.method.toUpperCase(),
            tags: route.tags || [],
            summary: route.summary || ""
        });
    }

    private processQueuedRoutes() {
        if (!this.app) return;
        for (const { route, handler } of this.queuedRoutes) {
            this.addRoute(route, handler);
        }
        this.queuedRoutes = [];
    }

    routes(app: Hono) {
        if (this.app) {
            app.route("/", this.app);
        }

        app.get("/openapi.json", (c: Context) => {
            if (!this.app) return c.json({ error: "OpenAPI not initialized" }, 500);

            const spec = this.app.getOpenAPIDocument({
                openapi: "3.1.0",
                info: {
                    title: this.config.title,
                    version: this.config.version,
                    description: this.config.description || "API Documentation",
                    contact: this.config.contact,
                    license: this.config.license
                },
                servers: this.config.servers || [{ url: "http://localhost:8000", description: "Dev Server" }],
                tags: this.config.tags || [],
                externalDocs: this.config.externalDocs,
                security: this.config.security
            });

            if (this.config.securitySchemes) {
                if (!spec.components) spec.components = {};
                spec.components.securitySchemes = this.config.securitySchemes;
            }

            return c.json(spec);
        });

        app.get("/docs", (c) => c.html(this.generateScalarHTML()));
    }

    private generateScalarHTML(): string {
        return `
<!DOCTYPE html>
<html>
<head>
    <title>${this.config.title} - API Documentation</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>body { margin: 0; padding: 0; }</style>
</head>
<body>
    <script id="api-reference" data-url="/openapi.json" data-configuration='{"theme":"purple","layout":"modern","showSidebar":true}'></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@latest"></script>
</body>
</html>`.trim();
    }
}

export { createRoute, OpenAPIHono, z };
