fn main() {
    // Tauri 2 deja que cualquier webview invoque todos los comandos de la app
    // salvo que se declaren aca. Declarados, cada uno necesita su permiso
    // `allow-<comando>` en una capability (capabilities/default.json); tauri-build
    // genera esos permisos en permissions/autogenerated/.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&["abrir_archivo", "app_info"])),
    )
    .expect("error al correr tauri-build");
}
