import { afterAll, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { App } from '@iskra-bun/core';
import type { Generated } from 'kysely';
import oracledb from 'oracledb';
import { OracleDriver } from '../src/driver';
import type { OracleBinds } from '../src/binds';
import { ConnectionError, QueryError } from '../src/errors';
import { paginateByCursor, search, sortBy, type CursorPage } from '../src/pagination';
import { ORACLE, oracleUp } from './oracle-env';

// The OracleDriver end to end against a real database: raw statements with
// typed binds, LOBs, Kysely, transactions, pagination and search. Skipped
// unless the database in oracle-env.ts is reachable; the `oracle` CI job
// provides one.
setDefaultTimeout(30_000);

const up = await oracleUp();
const T = 'ISKRA_IT_PEOPLE';

interface People {
    ID: Generated<number>;
    NAME: string;
    CITY: string | null;
    CREATED: Date;
    BIO: string | null;
    PHOTO: Buffer | null;
    BIG: number | null;
}
interface DB {
    ISKRA_IT_PEOPLE: People;
}

async function startDriver<D = DB>(config: Record<string, unknown> = {}) {
    const driver = new OracleDriver<D>();
    await driver.init(
        new App({ name: 'OracleIntegration', logger: { level: 'silent' }, oracle: { ...ORACLE, ...config } }),
    );
    await driver.start();
    return driver;
}

(up ? describe : describe.skip)('OracleDriver (real Oracle)', () => {
    let oracle: OracleDriver<DB>;
    const count = async (where: string, binds: OracleBinds = {}) =>
        (await oracle.query<{ N: number }>(`SELECT COUNT(*) AS n FROM ${T} WHERE ${where}`, binds))[0]!.N;

    beforeAll(async () => {
        oracle = await startDriver();
        await oracle.execute(
            `BEGIN EXECUTE IMMEDIATE 'DROP TABLE ${T} PURGE';
             EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
        );
        await oracle.execute(`
            CREATE TABLE ${T} (
                id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                name    VARCHAR2(100) NOT NULL,
                city    VARCHAR2(100),
                created TIMESTAMP NOT NULL,
                bio     CLOB,
                photo   BLOB,
                big     NUMBER(38)
            )`);
    });

    afterAll(async () => {
        if (!oracle) return;
        await oracle.execute(`DROP TABLE ${T} PURGE`).catch(() => {});
        await oracle.stop();
    });

    beforeEach(async () => {
        await oracle.execute(`TRUNCATE TABLE ${T}`);
    });

    /** 25 people, Person 01…25, alternating between two cities. */
    async function seed() {
        const created = new Date('2026-01-01T00:00:00Z');
        const rows = Array.from({ length: 25 }, (_, i) => ({
            name: `Person ${String(i + 1).padStart(2, '0')}`,
            city: i % 2 === 0 ? 'Rosario' : 'Córdoba',
            created: new Date(created.getTime() + i * 60_000),
        }));
        const { rowsAffected } = await oracle.executeMany(
            `INSERT INTO ${T} (name, city, created) VALUES (:name, :city, :created)`,
            rows,
        );
        expect(rowsAffected).toBe(25);
    }

    test('start() connected and ping() answers', async () => {
        expect(oracle.db).toBeDefined();
        expect(await oracle.ping()).toBe(true);
    });

    test('execute(): RETURNING INTO by type name, rowsAffected', async () => {
        const inserted = await oracle.execute(
            `INSERT INTO ${T} (name, created) VALUES (:name, :created) RETURNING id, name INTO :id, :stored`,
            {
                name: 'Ana',
                created: new Date(),
                id: { dir: 'returning', type: 'number' },
                stored: { dir: 'returning', type: 'string' },
            },
        );
        expect(inserted.rowsAffected).toBe(1);
        expect(inserted.outBinds.stored).toEqual(['Ana']);
        expect(Number.isInteger(inserted.outBinds.id[0])).toBe(true);

        const updated = await oracle.execute(`UPDATE ${T} SET city = :city WHERE name = :name`, {
            city: 'Rosario',
            name: 'Ana',
        });
        expect(updated.rowsAffected).toBe(1);
        const deleted = await oracle.execute(`DELETE FROM ${T} WHERE name = :name`, { name: 'nobody' });
        expect(deleted.rowsAffected).toBe(0);
    });

    test('execute(): PL/SQL OUT and IN OUT parameters by type name', async () => {
        const result = await oracle.execute(
            `BEGIN
                :greeting := 'hola ' || :who;
                :len := LENGTH(:who);
                :text := TO_CLOB(RPAD('x', 5000, 'x'));
                :stamp := TIMESTAMP '2026-01-02 03:04:05.678';
                :counter := :counter + 1;
             END;`,
            {
                who: 'Ana',
                greeting: { dir: 'out', type: 'string' },
                len: { dir: 'out', type: 'number' },
                text: { dir: 'out', type: 'clob' },
                stamp: { dir: 'out', type: 'timestamp' },
                counter: { dir: 'inout', type: 'number', val: 41 },
            },
        );
        expect(result.outBinds.greeting).toBe('hola Ana');
        expect(result.outBinds.len).toBe(3);
        expect(result.outBinds.text).toBe('x'.repeat(5000));
        expect(result.outBinds.stamp).toEqual(new Date(2026, 0, 2, 3, 4, 5, 678));
        expect(result.outBinds.counter).toBe(42);
    });

    test('CLOB columns read as strings and BLOB as Buffers, with raw SQL and Kysely', async () => {
        const bio = 'ñandú '.repeat(10) + 'x'.repeat(200_000);
        const photo = Buffer.from(Array.from({ length: 100_000 }, (_, i) => i % 251));
        await oracle.execute(`INSERT INTO ${T} (name, created, bio, photo) VALUES ('lob', :created, :bio, :photo)`, {
            created: new Date(),
            bio: { type: 'clob', val: bio },
            photo: { type: 'blob', val: photo },
        });
        const [raw] = await oracle.query<{ BIO: string; PHOTO: Buffer }>(`SELECT bio, photo FROM ${T}`);
        expect(raw!.BIO === bio).toBe(true);
        expect(Buffer.isBuffer(raw!.PHOTO) && raw!.PHOTO.equals(photo)).toBe(true);

        const row = await oracle.db!.selectFrom(T).select(['BIO', 'PHOTO']).executeTakeFirstOrThrow();
        expect(row.BIO === bio).toBe(true);
        expect(row.PHOTO!.equals(photo)).toBe(true);
    });

    test('fetchAsString: number keeps the digits of a NUMBER past 2^53', async () => {
        await oracle.execute(`INSERT INTO ${T} (name, created, big) VALUES ('big', :created, :big)`, {
            created: new Date(),
            big: '12345678901234567890123',
        });
        const exact = await startDriver({ fetchAsString: ['number'] });
        try {
            const [row] = await exact.query<{ BIG: string }>(`SELECT big FROM ${T}`);
            expect(row!.BIG).toBe('12345678901234567890123');
        } finally {
            await exact.stop();
        }
    });

    test('Kysely: typed insert, select, update and delete; limit() becomes FETCH NEXT', async () => {
        const db = oracle.db!;
        const created = new Date('2026-03-04T05:06:07.890Z');
        const insert = await db
            .insertInto(T)
            .values({ NAME: 'Bea', CITY: 'Rosario', CREATED: created })
            .executeTakeFirst();
        expect(insert.numInsertedOrUpdatedRows).toBe(1n);
        await db.insertInto(T).values({ NAME: 'Caro', CREATED: created }).execute();

        const bea = await db
            .selectFrom(T)
            .select(['ID', 'NAME', 'CITY', 'CREATED'])
            .where('NAME', '=', 'Bea')
            .execute();
        expect(bea).toEqual([{ ID: expect.any(Number), NAME: 'Bea', CITY: 'Rosario', CREATED: created }]);

        const update = await db.updateTable(T).set({ CITY: 'Córdoba' }).where('NAME', '=', 'Caro').executeTakeFirst();
        expect(update.numUpdatedRows).toBe(1n);

        const firstOne = await db.selectFrom(T).select('NAME').orderBy('NAME').limit(1).execute();
        expect(firstOne).toEqual([{ NAME: 'Bea' }]);

        const removed = await db.deleteFrom(T).where('NAME', 'in', ['Bea', 'Caro']).executeTakeFirst();
        expect(removed.numDeletedRows).toBe(2n);
    });

    test('transaction(): tx.execute and tx.db share it; rolled back on error, committed otherwise', async () => {
        const created = new Date();
        await expect(
            oracle.transaction(async (tx) => {
                await tx.execute(`INSERT INTO ${T} (name, created) VALUES ('Tx1', :created)`, { created });
                await tx.db.insertInto(T).values({ NAME: 'Tx2', CREATED: created }).execute();
                const inside = await tx.query<{ N: number }>(`SELECT COUNT(*) AS n FROM ${T} WHERE name LIKE 'Tx%'`);
                expect(inside[0]!.N).toBe(2);
                // Other connections do not see it before the commit. (oracle.query()
                // would join the transaction: it runs in its async context.)
                const other = await oracledb.getConnection(ORACLE);
                try {
                    const seen = await other.execute<[number]>(`SELECT COUNT(*) FROM ${T} WHERE name LIKE 'Tx%'`);
                    expect(seen.rows![0]![0]).toBe(0);
                } finally {
                    await other.close();
                }
                throw new Error('undo');
            }),
        ).rejects.toThrow('undo');
        expect(await count(`name LIKE 'Tx%'`)).toBe(0);

        await oracle.transaction((tx) =>
            tx.execute(`INSERT INTO ${T} (name, created) VALUES ('Tx3', :created)`, { created }),
        );
        expect(await count(`name = 'Tx3'`)).toBe(1);
    });

    test('Kysely transactions: db.transaction() rolls back, savepoints roll back part', async () => {
        const db = oracle.db!;
        const created = new Date();
        await expect(
            db.transaction().execute(async (trx) => {
                await trx.insertInto(T).values({ NAME: 'Kx1', CREATED: created }).execute();
                throw new Error('undo');
            }),
        ).rejects.toThrow('undo');
        expect(await count(`name = 'Kx1'`)).toBe(0);

        const trx = await db.startTransaction().execute();
        await trx.insertInto(T).values({ NAME: 'Kx2', CREATED: created }).execute();
        const sp = await trx.savepoint('before_kx3').execute();
        await sp.insertInto(T).values({ NAME: 'Kx3', CREATED: created }).execute();
        await sp.rollbackToSavepoint('before_kx3').execute();
        await trx.commit().execute();
        expect(await count(`name = 'Kx2'`)).toBe(1);
        expect(await count(`name = 'Kx3'`)).toBe(0);
    });

    test('paginate(): pages in order with the total', async () => {
        await seed();
        const q = oracle.db!.selectFrom(T).select(['ID', 'NAME']).orderBy('ID');
        const first = await oracle.paginate(q, { page: 1, pageSize: 10 });
        expect([first.total, first.pages, first.items.length]).toEqual([25, 3, 10]);
        expect(first.items[0]!.NAME).toBe('Person 01');
        const last = await oracle.paginate(q, { page: '3', pageSize: '10' });
        expect(last.items.map((p) => p.NAME)).toEqual([
            'Person 21',
            'Person 22',
            'Person 23',
            'Person 24',
            'Person 25',
        ]);
        const past = await oracle.paginate(q, { page: 9, pageSize: 10 });
        expect([past.items.length, past.total]).toEqual([0, 25]);
    });

    test('search(): case-insensitive across columns, wildcards match themselves; sortBy()', async () => {
        await seed();
        await oracle.executeMany(`INSERT INTO ${T} (name, city, created) VALUES (:name, :city, :created)`, [
            { name: '100% real', city: 'Rosario', created: new Date() },
            { name: 'a_b', city: 'Rosario', created: new Date() },
            { name: 'axb', city: 'Rosario', created: new Date() },
        ]);
        const base = () => oracle.db!.selectFrom(T).select(['NAME', 'CITY']);
        const inCordoba = await search(base(), ['NAME', 'CITY'], 'CÓRD').execute();
        expect(inCordoba).toHaveLength(12);
        expect((await search(base(), ['NAME'], 'person 0').execute()).length).toBe(9);
        expect((await search(base(), ['NAME'], '%').execute()).map((r) => r.NAME)).toEqual(['100% real']);
        expect((await search(base(), ['NAME'], '_').execute()).map((r) => r.NAME)).toEqual(['a_b']);

        const sorted = await sortBy(base(), '-CITY,NAME', ['CITY', 'NAME']).execute();
        expect(sorted[0]).toEqual({ NAME: '100% real', CITY: 'Rosario' });
        expect(sorted.at(-1)!.CITY).toBe('Córdoba');
    });

    test('paginateByCursor(): walks every page on composite keys without gaps or repeats', async () => {
        await seed();
        for (const direction of ['asc', 'desc'] as const) {
            const expected = await oracle
                .db!.selectFrom(T)
                .select(['ID', 'CITY'])
                .orderBy('CITY', direction)
                .orderBy('ID', direction)
                .execute();
            const seen: number[] = [];
            let after: string | null = null;
            let pages = 0;
            do {
                const page: CursorPage<{ ID: number; CITY: string | null }> = await paginateByCursor(
                    oracle.db!.selectFrom(T).select(['ID', 'CITY']),
                    {
                        keys: ['CITY', 'ID'],
                        direction,
                        pageSize: 7,
                        after,
                    },
                );
                seen.push(...page.items.map((p) => p.ID));
                after = page.nextCursor;
                pages++;
            } while (after);
            expect(pages).toBe(4);
            expect(seen).toEqual(expected.map((p) => p.ID));
        }
    });

    test('stream(): raw and Kysely', async () => {
        await seed();
        const raw: string[] = [];
        for await (const row of oracle.stream<{ NAME: string }>(`SELECT name FROM ${T} ORDER BY id`, [], {
            chunkSize: 4,
        })) {
            raw.push(row.NAME);
        }
        expect(raw).toHaveLength(25);
        expect(raw[24]).toBe('Person 25');

        let streamed = 0;
        for await (const row of oracle.db!.selectFrom(T).select('ID').orderBy('ID').stream(5)) {
            expect(typeof row.ID).toBe('number');
            streamed++;
        }
        expect(streamed).toBe(25);
    });

    test('camelCase: Kysely in camelCase over UPPER_SNAKE_CASE columns', async () => {
        await seed();
        const cc = await startDriver<{
            iskraItPeople: { id: Generated<number>; name: string; city: string | null; created: Date };
        }>({ camelCase: true });
        try {
            const rows = await cc
                .db!.selectFrom('iskraItPeople')
                .select(['id', 'name', 'city'])
                .where('name', '=', 'Person 02')
                .execute();
            expect(rows).toEqual([{ id: expect.any(Number), name: 'Person 02', city: 'Córdoba' }]);
        } finally {
            await cc.stop();
        }
    });

    test('errors carry the ORA number; setOnQuery sees statements', async () => {
        const seen: string[] = [];
        oracle.setOnQuery((sql) => seen.push(sql));
        try {
            await oracle.execute(`INSERT INTO ${T} (id, name, created) VALUES (1, 'a', :c)`, { c: new Date() });
            const error = (await oracle
                .execute(`INSERT INTO ${T} (id, name, created) VALUES (1, 'b', :c)`, { c: new Date() })
                .catch((e: unknown) => e)) as QueryError;
            expect(error).toBeInstanceOf(QueryError);
            expect(error.errorNum).toBe(1);
            expect(error.message).toStartWith('ORA-00001');
        } finally {
            oracle.setOnQuery(undefined);
        }
        expect(seen).toHaveLength(2);
    });

    test('start() rejects a wrong password with a ConnectionError', async () => {
        await expect(startDriver({ password: 'not-the-password' })).rejects.toThrow(ConnectionError);
        await expect(startDriver({ password: 'not-the-password' })).rejects.toThrow(/ORA-01017/);
    });
});
