import { afterAll, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { App } from '@iskra-bun/core';
import { sql, type Generated } from 'kysely';
import oracledb from 'oracledb';
import { OracleDriver } from '../src/driver';
import { DeadlineError, QueryError } from '../src/errors';
import { paginateByCursor, type CursorPage } from '../src/pagination';
import { ORACLE, oracleUp } from './oracle-env';

// Timeouts, cancellation, statements joining the active transaction, typed
// executeMany, unused binds, Kysely on older releases and microsecond cursor
// keys, against a real database. Skipped unless the database in
// oracle-env.ts is reachable; the `oracle` CI job provides 23ai and 21c.
setDefaultTimeout(60_000);

const up = await oracleUp();
const T = 'ISKRA_IT_STMT';

interface DB {
    ISKRA_IT_STMT: {
        ID: Generated<number>;
        NAME: string;
        CITY: string | null;
        CREATED: Generated<Date>;
        BODY: string | null;
    };
}

async function startDriver(config: Record<string, unknown> = {}) {
    const driver = new OracleDriver<DB>();
    await driver.init(
        new App({ name: 'OracleStatements', logger: { level: 'silent' }, oracle: { ...ORACLE, ...config } }),
    );
    await driver.start();
    return driver;
}

(up ? describe : describe.skip)('OracleDriver statements (real Oracle)', () => {
    let oracle: OracleDriver<DB>;

    beforeAll(async () => {
        oracle = await startDriver();
        await oracle.execute(
            `BEGIN EXECUTE IMMEDIATE 'DROP TABLE ${T} PURGE';
             EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
        );
        await oracle.execute(`
            CREATE TABLE ${T} (
                id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                name    VARCHAR2(100) NOT NULL,
                city    VARCHAR2(100),
                created TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                body    CLOB
            )`);
    });

    afterAll(async () => {
        if (!oracle) return;
        await oracle.execute(`DROP TABLE ${T} PURGE`).catch(() => {});
        await oracle.stop();
    });

    beforeEach(async () => {
        await oracle.execute(`TRUNCATE TABLE ${T}`);
    });

    /** Holds a row lock on another connection while `fn` runs. */
    async function whileLocked(fn: () => Promise<void>) {
        await oracle.execute(`INSERT INTO ${T} (id, name) VALUES (1, 'locked')`);
        const holder = await oracledb.getConnection(ORACLE);
        try {
            await holder.execute(`SELECT id FROM ${T} WHERE id = 1 FOR UPDATE`);
            await fn();
        } finally {
            await holder.rollback();
            await holder.close();
        }
    }

    test('a timeout ends a statement waiting on a lock, and the pool keeps serving', async () => {
        // node-oracledb's cancel travels in band and a session waiting on a
        // lock may not read it: then no NJS-123 comes, and the deadline
        // (timeout + deadlineGrace, 2 s here) gives up on the connection.
        await whileLocked(async () => {
            const started = performance.now();
            const error = (await oracle
                .execute(`UPDATE ${T} SET name = 'waited' WHERE id = 1`, {}, { timeout: 1000 })
                .catch((e: unknown) => e)) as QueryError;
            expect(error).toBeInstanceOf(QueryError);
            expect(error.timedOut).toBe(true);
            if (error instanceof DeadlineError) expect(error.deadlineMs).toBe(2000);
            expect(performance.now() - started).toBeLessThan(5000);
            expect(await oracle.queryOne<{ ONE: number }>('SELECT 1 AS one FROM DUAL')).toEqual({ ONE: 1 });
        });
        // Its outcome is not asserted: an UPDATE outside a transaction that
        // the database never cancelled runs, and commits, once the lock frees.
    });

    test('a given up connection goes back to the pool at once', async () => {
        const small = await startDriver({ pool: { max: 1, queueTimeout: 3000 }, deadlineGrace: 0 });
        try {
            await whileLocked(async () => {
                await expect(
                    small.execute(`UPDATE ${T} SET name = 'waited' WHERE id = 1`, {}, { timeout: 500 }),
                ).rejects.toThrow();
                // With one connection, the next statement waits for the lost one to leave.
                expect(await small.queryOne<{ ONE: number }>('SELECT 1 AS one FROM DUAL')).toEqual({ ONE: 1 });
            });
        } finally {
            await small.stop();
        }
    });

    test('a transaction with a statement past its deadline is lost, and the database rolls it back', async () => {
        const strict = await startDriver({ deadlineGrace: 0, pool: { max: 2 } });
        try {
            await oracle.execute(`INSERT INTO ${T} (id, name, city) VALUES (2, 'other', 'before')`);
            await whileLocked(async () => {
                const error = await strict
                    .transaction(async (tx) => {
                        await tx.execute(`UPDATE ${T} SET city = 'tx' WHERE id = 2`);
                        await tx.execute(`UPDATE ${T} SET name = 'waited' WHERE id = 1`, {}, { timeout: 1000 });
                    })
                    .catch((e: unknown) => e);
                expect((error as QueryError).timedOut).toBe(true);
            });
            // Neither UPDATE commits: the session dies once it answers, and the database rolls it back.
            await Bun.sleep(500);
            expect(await strict.query(`SELECT id, name, city FROM ${T} ORDER BY id`)).toEqual([
                { ID: 1, NAME: 'locked', CITY: null },
                { ID: 2, NAME: 'other', CITY: 'before' },
            ]);
        } finally {
            await strict.stop();
        }
    });

    test('an AbortSignal cancels a statement waiting on a lock', async () => {
        await whileLocked(async () => {
            const controller = new AbortController();
            setTimeout(() => controller.abort(), 300);
            const error = (await oracle
                .execute(
                    `UPDATE ${T} SET name = 'waited' WHERE id = 1`,
                    {},
                    { signal: controller.signal, timeout: 10_000 },
                )
                .catch((e: unknown) => e)) as QueryError;
            expect(error).toBeInstanceOf(QueryError);
            expect(error.errorCode).toBe('ORA-01013');
        });
    });

    test('ping() answers false within pingTimeout while the pool has no free connection', async () => {
        const small = await startDriver({ pool: { max: 1, queueTimeout: 20_000 }, pingTimeout: 500 });
        try {
            await small.transaction(async () => {
                const started = performance.now();
                expect(await small.ping()).toBe(false);
                expect(performance.now() - started).toBeLessThan(3000);
            });
            expect(await small.ping()).toBe(true);
        } finally {
            await small.stop();
        }
    });

    test('inside transaction(), oracle.execute() joins it instead of waiting on its locks', async () => {
        await oracle.execute(`INSERT INTO ${T} (id, name) VALUES (1, 'a')`);
        await oracle.transaction(async (tx) => {
            await tx.execute(`UPDATE ${T} SET name = 'b' WHERE id = 1`);
            // On another connection this would wait for the row lock above.
            await oracle.execute(`UPDATE ${T} SET city = 'Rosario' WHERE id = 1`, {}, { timeout: 5000 });
            await oracle.db!.updateTable(T).set({ CITY: 'Córdoba' }).where('ID', '=', 1).execute();
        });
        expect(
            await oracle.queryOne<{ NAME: string; CITY: string }>(`SELECT name, city FROM ${T} WHERE id = 1`),
        ).toEqual({
            NAME: 'b',
            CITY: 'Córdoba',
        });
        await expect(oracle.transaction(() => oracle.transaction(async () => 1))).rejects.toThrow(
            'no nested transactions',
        );
    });

    test('queryOne(), and unused binds refused or dropped', async () => {
        await oracle.executeMany(`INSERT INTO ${T} (name) VALUES (:name)`, [{ name: 'a' }, { name: 'b' }]);
        expect(await oracle.queryOne<{ NAME: string }>(`SELECT name FROM ${T} ORDER BY name`)).toEqual({ NAME: 'a' });

        const error = (await oracle
            .query(`SELECT name FROM ${T} WHERE name = :name`, { name: 'a', extra: 1 })
            .catch((e: unknown) => e)) as QueryError;
        expect(error).toBeInstanceOf(QueryError);
        expect(error.errorCode).toMatch(/^NJS-/);
        expect(
            await oracle.query(
                `SELECT name FROM ${T} WHERE name = :name`,
                { name: 'a', extra: 1 },
                { dropUnusedBinds: true },
            ),
        ).toEqual([{ NAME: 'a' }]);
    });

    test('executeMany() loads CLOBs with a typed bind and returns the RETURNING ids of each row', async () => {
        const long = 'ñandú '.repeat(10) + 'x'.repeat(100_000);
        const result = await oracle.executeMany(
            `INSERT INTO ${T} (name, body) VALUES (:name, :body) RETURNING id INTO :id`,
            [
                { name: 'long', body: { type: 'clob', val: long } },
                { name: 'short', body: { type: 'clob', val: 'short text' } },
            ],
            { bindDefs: { id: { dir: 'returning', type: 'number' } } },
        );
        expect(result.rowsAffected).toBe(2);
        const ids = result.outBinds.map((o) => (o as { id: number[] }).id[0]);
        expect(ids.every((id) => Number.isInteger(id))).toBe(true);
        const rows = await oracle.query<{ NAME: string; BODY: string }>(`SELECT name, body FROM ${T} ORDER BY id`);
        expect(rows.map((r) => r.NAME)).toEqual(['long', 'short']);
        expect(rows[0]!.BODY === long).toBe(true);
        expect(rows[1]!.BODY).toBe('short text');
    });

    test('Kysely: selectNoFrom reads FROM DUAL, MERGE runs, multi-row VALUES as the database allows', async () => {
        const db = oracle.db!;
        expect(await db.selectNoFrom(sql<number>`1`.as('one')).executeTakeFirstOrThrow()).toEqual({ one: 1 });

        await oracle.execute(`INSERT INTO ${T} (id, name) VALUES (1, 'a')`);
        const merged = await db
            .mergeInto(`${T} as t`)
            .using(`${T} as s`, 't.ID', 's.ID')
            .whenMatched()
            .thenUpdateSet({ CITY: 'Rosario' })
            .executeTakeFirst();
        expect(merged.numChangedRows).toBe(1n);
        expect(await oracle.queryOne<{ CITY: string }>(`SELECT city FROM ${T} WHERE id = 1`)).toEqual({
            CITY: 'Rosario',
        });

        const rows = [{ NAME: 'x' }, { NAME: 'y' }];
        expect(() => db.insertInto(T).values(rows).compile()).toThrow('an INSERT of several rows with VALUES');
        if ((oracle.serverVersion ?? 0) >= 23) {
            const modern = await startDriver({ compatibility: '23ai' });
            try {
                const inserted = await modern.db!.insertInto(T).values(rows).executeTakeFirst();
                expect(inserted.numInsertedOrUpdatedRows).toBe(2n);
            } finally {
                await modern.stop();
            }
        }
    });

    test('paginateByCursor() walks TIMESTAMP(6) keys that share a millisecond, without repeats or gaps', async () => {
        await oracle.executeMany(
            `INSERT INTO ${T} (name, created)
             VALUES (:name, TIMESTAMP '2026-01-01 00:00:00.123000' + NUMTODSINTERVAL(:micros / 1000000, 'SECOND'))`,
            Array.from({ length: 10 }, (_, i) => ({ name: `row ${i + 1}`, micros: i + 1 })),
        );
        const seen: string[] = [];
        let after: string | null = null;
        do {
            const page: CursorPage<{ NAME: string; CREATED: Date }> = await paginateByCursor(
                oracle.db!.selectFrom(T).select(['NAME', 'CREATED']),
                {
                    keys: [{ key: 'CREATED', type: 'timestamp' }],
                    pageSize: 3,
                    after,
                },
            );
            seen.push(...page.items.map((r) => r.NAME));
            after = page.nextCursor;
        } while (after);
        expect(seen).toEqual(Array.from({ length: 10 }, (_, i) => `row ${i + 1}`));

        await expect(
            paginateByCursor(oracle.db!.selectFrom(T).select(['NAME', 'CREATED']), { keys: ['CREATED'] }),
        ).rejects.toThrow("type: 'timestamp'");
    });
});
