import { afterAll, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import oracledb from 'oracledb';
import { ORACLE, oracleUp } from './oracle-env';

// oracledb in Thin mode (pure JavaScript, no Oracle Client) inside the Bun
// process, against a real database: what an in-process OracleDriver would rely
// on instead of the Node bridge. Skipped unless the database in oracle-env.ts
// is reachable; the `oracle` CI job provides one.
setDefaultTimeout(30_000);

const up = await oracleUp();
const TABLE = 'iskra_it_thin';
const OBJECT = { outFormat: oracledb.OUT_FORMAT_OBJECT };

// The out bind types the driver is to accept by name, and the DbType each maps to.
const OUT_TYPES = {
    string: oracledb.DB_TYPE_VARCHAR,
    number: oracledb.DB_TYPE_NUMBER,
    date: oracledb.DB_TYPE_DATE,
    timestamp: oracledb.DB_TYPE_TIMESTAMP,
    clob: oracledb.DB_TYPE_CLOB,
    raw: oracledb.DB_TYPE_RAW,
};

type Lob = { getData(): Promise<string | Buffer>; destroy(): void };

async function dropTable(conn: oracledb.Connection) {
    await conn.execute(
        `BEGIN EXECUTE IMMEDIATE 'DROP TABLE ${TABLE} PURGE';
         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
    );
}

(up ? describe : describe.skip)('oracledb Thin mode in Bun (real Oracle)', () => {
    let conn: oracledb.Connection;

    beforeAll(async () => {
        conn = await oracledb.getConnection(ORACLE);
        await dropTable(conn);
        await conn.execute(`
            CREATE TABLE ${TABLE} (
                id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                name    VARCHAR2(100) NOT NULL,
                amount  NUMBER(20, 2),
                big     NUMBER(38),
                created DATE,
                stamp   TIMESTAMP,
                body    CLOB,
                data    BLOB
            )`);
    });

    afterAll(async () => {
        if (!conn) return;
        await dropTable(conn);
        await conn.close();
    });

    beforeEach(async () => {
        await conn.execute(`TRUNCATE TABLE ${TABLE}`);
    });

    test('connects in-process in Thin mode', async () => {
        expect(oracledb.thin).toBe(true);
        expect(conn.oracleServerVersion).toBeGreaterThan(0);
        const result = await conn.execute('SELECT 1 AS one FROM DUAL', [], OBJECT);
        expect(result.rows).toEqual([{ ONE: 1 }]);
    });

    test('binds by name and by position', async () => {
        await conn.execute(
            `INSERT INTO ${TABLE} (name, amount) VALUES (:name, :amount)`,
            { name: 'Ana', amount: 10.5 },
            { autoCommit: true },
        );
        const result = await conn.execute(`SELECT name, amount FROM ${TABLE} WHERE name = :1`, ['Ana'], OBJECT);
        expect(result.rows).toEqual([{ NAME: 'Ana', AMOUNT: 10.5 }]);
    });

    test('reports rowsAffected for INSERT, UPDATE and DELETE', async () => {
        const inserted = await conn.executeMany(
            `INSERT INTO ${TABLE} (name, amount) VALUES (:name, :amount)`,
            [
                { name: 'a', amount: 1 },
                { name: 'b', amount: 2 },
                { name: 'c', amount: 3 },
            ],
            { autoCommit: true },
        );
        expect(inserted.rowsAffected).toBe(3);

        const updated = await conn.execute(
            `UPDATE ${TABLE} SET amount = amount * 10 WHERE amount >= :min`,
            { min: 2 },
            { autoCommit: true },
        );
        expect(updated.rowsAffected).toBe(2);

        const deleted = await conn.execute(`DELETE FROM ${TABLE} WHERE name = :name`, { name: 'nobody' });
        expect(deleted.rowsAffected).toBe(0);

        const selected = await conn.execute(`SELECT name FROM ${TABLE}`);
        expect(selected.rowsAffected).toBeUndefined();
    });

    test('returns DML RETURNING INTO out binds by name', async () => {
        const result = await conn.execute(
            `INSERT INTO ${TABLE} (name) VALUES (:name) RETURNING id, name INTO :id, :stored`,
            {
                name: 'Bo',
                id: { dir: oracledb.BIND_OUT, type: OUT_TYPES.number },
                stored: { dir: oracledb.BIND_OUT, type: OUT_TYPES.string, maxSize: 100 },
            },
            { autoCommit: true },
        );
        // One value per affected row.
        const out = result.outBinds as { id: number[]; stored: string[] };
        expect(result.rowsAffected).toBe(1);
        expect(out.stored).toEqual(['Bo']);
        expect(out.id).toHaveLength(1);
        expect(Number.isInteger(out.id[0])).toBe(true);
    });

    test('returns PL/SQL out binds of every named type', async () => {
        const out = (type: oracledb.DbType, maxSize?: number) => ({ dir: oracledb.BIND_OUT, type, maxSize });
        const result = await conn.execute(
            `BEGIN
                :s := 'hola ' || :who;
                :n := 42.5;
                :d := DATE '2026-01-02';
                :t := TIMESTAMP '2026-01-02 03:04:05.678';
                :c := TO_CLOB('texto largo');
                :r := HEXTORAW('DEADBEEF');
             END;`,
            {
                who: 'Ana',
                s: out(OUT_TYPES.string, 100),
                n: out(OUT_TYPES.number),
                d: out(OUT_TYPES.date),
                t: out(OUT_TYPES.timestamp),
                c: out(OUT_TYPES.clob),
                r: out(OUT_TYPES.raw, 4),
            },
        );
        const binds = result.outBinds as { s: string; n: number; d: Date; t: Date; c: Lob; r: Buffer };
        expect(binds.s).toBe('hola Ana');
        expect(binds.n).toBe(42.5);
        // DATE and TIMESTAMP carry no time zone: read as local time.
        expect(binds.d).toEqual(new Date(2026, 0, 2));
        expect(binds.t).toEqual(new Date(2026, 0, 2, 3, 4, 5, 678));
        expect(await binds.c.getData()).toBe('texto largo');
        binds.c.destroy();
        expect(binds.r).toEqual(Buffer.from('deadbeef', 'hex'));
    });

    test('reads a 1 MB CLOB and a BLOB as a Lob, with fetchInfo, and with fetchAsString/fetchAsBuffer', async () => {
        // Past one packet and past the 32 KiB of a VARCHAR2 bind.
        const body = 'ñandú '.repeat(10) + 'x'.repeat(1_000_000);
        const data = Buffer.from(Array.from({ length: 300_000 }, (_, i) => i % 251));
        await conn.execute(
            `INSERT INTO ${TABLE} (name, body, data) VALUES ('lob', :body, :data)`,
            { body: { val: body, type: oracledb.CLOB }, data: { val: data, type: oracledb.BLOB } },
            { autoCommit: true },
        );
        const sql = `SELECT body, data FROM ${TABLE} WHERE name = 'lob'`;
        const same = (row: { BODY: unknown; DATA: unknown }) => {
            expect(typeof row.BODY).toBe('string');
            expect((row.BODY as string).length).toBe(body.length);
            expect(row.BODY === body).toBe(true);
            expect(Buffer.isBuffer(row.DATA)).toBe(true);
            expect((row.DATA as Buffer).equals(data)).toBe(true);
        };

        // By default a LOB column is fetched as a Lob to read on its own.
        const lobs = (await conn.execute<{ BODY: Lob; DATA: Lob }>(sql, [], OBJECT)).rows![0];
        same({ BODY: await lobs.BODY.getData(), DATA: await lobs.DATA.getData() });

        const perQuery = await conn.execute<{ BODY: unknown; DATA: unknown }>(sql, [], {
            ...OBJECT,
            fetchInfo: { BODY: { type: oracledb.STRING }, DATA: { type: oracledb.BUFFER } },
        });
        same(perQuery.rows![0]);

        const { fetchAsString, fetchAsBuffer } = oracledb;
        oracledb.fetchAsString = [oracledb.CLOB];
        oracledb.fetchAsBuffer = [oracledb.BLOB];
        try {
            const global = await conn.execute<{ BODY: unknown; DATA: unknown }>(sql, [], OBJECT);
            same(global.rows![0]);
        } finally {
            oracledb.fetchAsString = fetchAsString;
            oracledb.fetchAsBuffer = fetchAsBuffer;
        }
    });

    test('commits and rolls back transactions', async () => {
        const other = await oracledb.getConnection(ORACLE);
        const count = async (c: oracledb.Connection, name: string) =>
            (await c.execute<[number]>(`SELECT COUNT(*) FROM ${TABLE} WHERE name = :name`, { name })).rows![0][0];
        try {
            // autoCommit is off by default: the insert is only this session's.
            await conn.execute(`INSERT INTO ${TABLE} (name) VALUES ('pending')`);
            expect(await count(conn, 'pending')).toBe(1);
            expect(await count(other, 'pending')).toBe(0);
            await conn.rollback();
            expect(await count(conn, 'pending')).toBe(0);

            await conn.execute(`INSERT INTO ${TABLE} (name) VALUES ('kept')`);
            await conn.commit();
            expect(await count(other, 'kept')).toBe(1);
        } finally {
            await other.close();
        }
    });

    test('createPool: separate sessions up to poolMax, queue timeout, reuse, close', async () => {
        const pool = await oracledb.createPool({
            ...ORACLE,
            poolMin: 0,
            poolMax: 3,
            poolIncrement: 1,
            queueTimeout: 1000,
        });
        try {
            const conns = await Promise.all([0, 1, 2].map(() => pool.getConnection()));
            const sids = await Promise.all(
                conns.map(
                    async (c) =>
                        (await c.execute<[string]>(`SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL`)).rows![0][0],
                ),
            );
            expect(new Set(sids).size).toBe(3);
            expect(pool.connectionsInUse).toBe(3);

            // poolMax reached: a fourth request waits queueTimeout, then fails.
            await expect(pool.getConnection()).rejects.toThrow(/NJS-040/);

            await Promise.all(conns.map((c) => c.close()));
            expect(pool.connectionsInUse).toBe(0);
            const reused = await pool.getConnection();
            expect(pool.connectionsOpen).toBeLessThanOrEqual(3);
            await reused.close();
        } finally {
            await pool.close(0);
        }
        expect(pool.status).toBe(oracledb.POOL_STATUS_CLOSED);
    });

    test('round-trips dates, numbers, NULLs and Unicode', async () => {
        const created = new Date('2026-01-02T03:04:05Z');
        const stamp = new Date('2026-01-02T03:04:05.678Z');
        await conn.execute(
            `INSERT INTO ${TABLE} (name, amount, big, created, stamp)
             VALUES (:name, :amount, :big, :created, :stamp)`,
            { name: 'Ñandú 🚀', amount: 12345.67, big: '12345678901234567890123', created, stamp },
            { autoCommit: true },
        );
        const result = await conn.execute<Record<string, unknown>>(
            `SELECT name, amount, big, created, stamp, body FROM ${TABLE}`,
            [],
            // A NUMBER past 2^53 loses digits as a JS number: fetched as a string.
            { ...OBJECT, fetchInfo: { BIG: { type: oracledb.STRING } } },
        );
        expect(result.rows).toEqual([
            {
                NAME: 'Ñandú 🚀',
                AMOUNT: 12345.67,
                BIG: '12345678901234567890123',
                CREATED: created,
                STAMP: stamp,
                BODY: null,
            },
        ]);
    });

    test('rejects with the ORA error code', async () => {
        const error = (await conn.execute('SELECT * FROM iskra_no_such_table').catch((e: unknown) => e)) as {
            message: string;
            errorNum?: number;
        };
        expect(error.message).toMatch(/^ORA-00942/);
        expect(error.errorNum).toBe(942);

        await expect(oracledb.getConnection({ ...ORACLE, password: 'not-the-password' })).rejects.toThrow(/ORA-01017/);
    });
});
