-- The users the Oracle example lists (GET /oracle/users).
CREATE TABLE app_users (
    id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100) NOT NULL,
    created TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX app_users_name ON app_users (name);
